### ISSUE TITLE
Crashing in x86 32-bit systems

### ISSUE THREAD

**Issue by kurtheiligmann** [TGIO/RNCryptorNative#8] opened 2016-09-06 23:25 UTC
We are seeing a crash in 32-bit x86 emulators (we don't have a device matching those specs). We tested on 2012 Nexus 7 device (arm), Nexus 9 device (64-bit), Motorola E 2nd gen (64-bit) device, arm7 emulator, arm8 emulator, and 64-bit emulator without crash. All 32-bit emulator device/API levelsetups crash in the `new RNCryptorNative()` call with the error below. Run the project at https://github.com/kurtheiligmann/RNCryptorNativeTest on an x86 emulator with the specs below (Nexus 5x, x86,  and API level 23)to reproduce the crash. 
### Stack trace

```
Process: com.rncryptornativetest, PID: 3869
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.rncryptornativetest-1/lib/x86/librncrypto.so"...
     at java.lang.Runtime.loadLibrary(Runtime.java:372)
     at java.lang.System.loadLibrary(System.java:1076)
     at tgio.rncryptor.RNCryptorNative.<clinit>(RNCryptorNative.java:33)
     at com.rncryptornativetest.MainActivity.onCreate(MainActivity.java:14)
     at android.app.Activity.performCreate(Activity.java:6237)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
     at android.app.ActivityThread.-wrap11(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
### Emulator specs

Name: Nexus_5X_API_23_32-bit
CPU/ABI: Google APIs Intel Atom (x86)
Path: /{local path}/avd/Nexus_5X_API_23_32-bit.avd
Target: google_apis [Google APIs](API level 23)
Skin: nexus_5x
SD Card: 100M
hw.lcd.density: 420
hw.dPad: no
avd.ini.encoding: UTF-8
hw.camera.back: none
disk.dataPartition.size: 800M
hw.gpu.enabled: yes
runtime.network.latency: none
hw.keyboard: yes
runtime.network.speed: full
hw.device.hash2: MD5:1be89bc42ec9644d4b77968b23474980
hw.ramSize: 1536
tag.id: google_apis
tag.display: Google APIs
hw.sdCard: yes
hw.device.manufacturer: Google
hw.mainKeys: no
hw.accelerometer: yes
hw.trackBall: no
hw.device.name: Nexus 5X
hw.sensors.proximity: yes
hw.gpu.mode: auto
hw.battery: yes
AvdId: Nexus_5X_API_23_32-bit
image.sysdir.1: system-images/android-23/google_apis/x86/
hw.sensors.orientation: yes
hw.audioInput: yes
hw.camera.front: none
hw.gps: yes
avd.ini.displayname: Nexus 5X API 23 32-bit
vm.heapSize: 64
image.androidVersion.api: 23
runtime.scalefactor: auto

**Comment by kurtheiligmann** [comment] 2016-09-08 22:55
Fixed by using the experimental gradle plugin. See the fixed branch (https://github.com/kurtheiligmann/RNCryptorNativeTest/tree/fixed) in the repo above. Is there a fix that could be applied to this library? If not, feel free to close, but maybe put something in the README about using the experimental plugin.

**Comment by DefiantCatgirl** [comment] 2016-09-19 09:53
Confirming that x86 devices also crash, according to our crash analytics. Will confirm and report back if the gradle fix works for those.

The problem is that we can't use Crashlytics with gradle-experimental so this will require some hacks and crutches.

**Comment by appcoders** [comment] 2016-10-18 17:49
@TGIO  @getsadzeg Which version of gcc did you use to create the shared library objects 
libgnustl_shared.so and libcryptopp_shared.so ? I think the problem occurs because the compiler used on my machine is different to yours. https://github.com/facebook/react-native/issues/9410#issuecomment-240646011

**Comment by getsadzeg** [comment] 2016-10-23 16:25
@kurtheiligmann Please create the PR.

@appcoders It says I'm using gcc 5.1.1

**Comment by mandelmonkey** [comment] 2016-11-21 06:25
I am also getting this error, is there a way to fix this?

**Comment by getsadzeg** [comment] 2016-11-22 16:10
@kurtheiligmann created branch which fixes this, but he didn't create the PR.

@kurtheiligmann create PR, please.

**Comment by kurtheiligmann** [comment] 2016-11-22 16:54
The my fixes are all app level changes, not changes with the library. 

Using the experimental gradle plugin stopped the crash for me.

**Comment by mandelmonkey** [comment] 2016-11-22 18:15
I cannot use  experimental gradle plugin because it throws another error
for a plugin i am using, is there another way to fix this?

**Comment by getsadzeg** [comment] 2016-11-22 18:19
Oh, got it.

I don't know the solution, unfortunately.

**Comment by mandelmonkey** [comment] 2016-11-23 17:05
@kurtheiligmann It still crashes with experimental plugin

Was that all you changed?

11-24 02:05:00.078 4852-4852/com.mandelduck.takara E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.mandelduck.takara, PID: 4852
                                                                     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.mandelduck.takara-1/lib/x86/librncrypto.so"...
                                                                         at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                         at java.lang.System.loadLibrary(System.java:1530)
                                                                         at tgio.rncryptor.RNCryptorNative.<clinit>(RNCryptorNative.java:33)
                                                                         at com.mandelduck.takara.MapsActivity.<init>(MapsActivity.java:167)
                                                                         at java.lang.Class.newInstance(Native Method)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by kurtheiligmann** [comment] 2016-11-23 17:35
Check the diff at https://github.com/kurtheiligmann/RNCryptorNativeTest/pull/1/files and see if anything in there helps. Outside of that, IDK.

**Comment by mandelmonkey** [comment] 2016-11-23 18:12
@kurtheiligmann 

thanks, I cloned your fixed pull request code and ran it, then android studio said

Error:The project is using an incompatible version of the Android Gradle Experimental plugin.
Please update your project to use version 0.8.2.

after that update the same error was thrown

ava.lang.UnsatisfiedLinkError: dlopen failed:   x86/librncrypto.so"...

**Comment by mandelmonkey** [comment] 2017-03-19 16:52
any update on this?

**Comment by getsadzeg** [comment] 2017-03-19 19:37
See pull request opened by @kurtheiligmann . It's chance that it will help you.

**Comment by getsadzeg** [comment] 2017-03-26 16:37
@mandelmonkey Update [this line](https://github.com/kurtheiligmann/RNCryptorNativeTest/pull/1/files#diff-c197962302397baf3a4cc36463dce5eaR8) in your code with 0.8.2 and please write if it fixes problem for you. And for that exception, you can see [this answer](http://stackoverflow.com/a/32846340).

**Comment by getsadzeg** [comment] 2017-03-26 17:07
I just got around with @appcoders ' comments and the problem seems solvable. I think it's about compiler differencies between yours and one's which compiled shared libraries initially, or something like that.

Take a look [at this comment](https://github.com/facebook/react-native/issues/9410#issuecomment-240646011), it seems someone got same problem with react-native.

**Comment by oskitar89** [comment] 2017-04-12 09:38
I am also getting this error with Android 7.0 emulator (genymotion), but it works with a real mobile with Android 5.1 x86 and Android 7.1.1 x86 emulator.  Is there a way to fix this? With Android Gradle Experimental don't work.

**Comment by andygeers** [comment] 2017-06-16 14:49
Any news on this issue?

**Comment by TGIO** [comment] 2017-06-16 15:05
planning upgrade soon

**Comment by andygeers** [comment] 2017-06-16 16:39
@TGIO Thank you for your efforts on this - this library is just about the only sane option for cross-platform encryption and your work is very much appreciated.

**Comment by TGIO** [comment] 2017-06-17 13:13
fixed with https://github.com/TGIO/RNCryptorNative/commit/5209f10b988e4033c0b769a40b0d6cc99ea16af7

**Closed as completed by TGIO** 2017-06-17 13:13 UTC
Labels: bug
